### ISSUE TITLE
Flux reconstruction through DG

### ISSUE THREAD

**Issue by dougshidong** [dougshidong/PHiLiP#11]
According to

@Article{Zwanenburg2016,
  author    = {Zwanenburg, Philip and Nadarajah, Siva},
  title     = {Equivalence between the energy stable flux reconstruction and filtered discontinuous {G}alerkin schemes},
  journal   = {Journal of Computational Physics},
  year      = {2016},
  volume    = {306},
  month     = feb,
  pages     = {343--369},
  doi       = {10.1016/j.jcp.2015.11.036},
  file      = {:HigherOrder/Zwanenburg2016 - Equivalence between the Energy Stable Flux Reconstruction and Filtered Discontinuous Galerkin Schemes.pdf:},
  publisher = {Elsevier BV},
}

We can implement FR by adding a modal filter to DG equivalent to the FR correction field.

**Comment by jbrillon** [comment]
Addressed by PR #111
