### ISSUE TITLE
Investigate TRANSONIC test case

### ISSUE THREAD

**Issue by dougshidong** [dougshidong/PHiLiP#112]
@jbrillon and @AlexanderCicchino have reported long runtimes of the TRANSONIC test case >24 hours. On my branch which dates back from Oct 2021, it takes around 2.5 hours with 6 cores.

The likely changes to this test case is the artificial dissipation introduced by @PranshulThakur. Could you please investigate whether your changes have caused a drop in performance of the transonic test case?

**Comment by PranshulThakur** [comment]
Hmm, that's strange. I ran ctest a while ago and all the 186 tests were done within 9-10 hours with 6 cores. @jbrillon and @AlexanderCicchino, can you please mention the conditions under which that particular test took >24 hours (cores, memory, etc)? I will try changing artificial dissipation's implementation to see if it can be made faster.

**Comment by PranshulThakur** [comment]
@dougshidong , @jbrillon , @AlexanderCicchino , I ran `2D_EULER_INTEGRATION_NACA0012_TRANSONIC_LONG` of master on my local machine with 4 cores and it took around 4 hours. I have attached the log file.
[Euler_Transonic.log](https://github.com/dougshidong/PHiLiP/files/8383745/Euler_Transonic.log)

**Comment by PranshulThakur** [comment]
According to my conversation with @AlexanderCicchino , it works fine on his master branch too. @jbrillon, can you confirm the issue by running it on your local machine to see if the issue is in master or in another branch?

**Comment by PranshulThakur** [comment]
Hmm, so the residual converges but the test does not pass? That's weird. Can you try commenting out this line in assemble_face_term() in weak_dg.cpp: https://github.com/dougshidong/PHiLiP/blob/master/src/dg/weak_dg.cpp#L2136?

**Comment by dougshidong** [comment]
With the recent changes with the FlowSolver class, I noticed that the 2D_EULER_INTEGRATION_NACA0012_TRANSONIC_LONG might not ramp up the polynomial anymore starting from p0. @jbrillon @donovan97 @PranshulThakur , can you confirm?

**Comment by donovan97** [comment]
You need it to do ode_solver->initialize_steady_polynomial_ramping instead of ode_solver->steady_state? If so, that's a simple fix and I can make a quick PR to take care of it.
