### ISSUE TITLE
Generalize Initial Condition to handle arbitrary projections

### ISSUE THREAD

**Issue by AlexanderCicchino** [dougshidong/PHiLiP#123]
The current initial condition class currently doesn't have the capability to project the IC for the solution. This is imperative for curvilinear unsteady test cases. Solving will have to have the IC store an operators object and project appropriately.

**Comment by dougshidong** [comment]
https://github.com/dougshidong/PHiLiP/pull/111#discussion_r842883202

**Comment by AlexanderCicchino** [comment]
Completed.
