### ISSUE TITLE
Compute conservation and energy within ODESolverBase.

### ISSUE THREAD

**Issue by AlexanderCicchino** [dougshidong/PHiLiP#127]
Have ODESolverBase compute and store energy and conservation for unsteady problems for all timesteps.

**Comment by dougshidong** [comment]
An ODE solver should not require knowledge of "energy" and "conservation". ODESolver should eventually be replaced by some form of:

https://www.dealii.org/developer/doxygen/deal.II/classTimeStepping_1_1TimeStepping.html
