### ISSUE TITLE
Surface split forms for all physics other than Burgers'

### ISSUE THREAD

**Issue by AlexanderCicchino** [dougshidong/PHiLiP#128]
Currently, only Burgers' has surface splitting. Euler, MHD, etc need their respective forms.

**Comment by jbrillon** [comment]
See comment https://github.com/dougshidong/PHiLiP/pull/111/files#r844667894

**Comment by cpethrick** [comment]
Now that PR #111 has been merged, split forms for Burgers' and Euler are in the code. Are we planning to add split forms for any other PDEs?


Also, is there any `abort()` statement if a user tries to select a split form for a PDE which doesn't have a split form implemented? I didn't find one in a quick search of the dg_factory and physics_factory. I think we could close this issue if there is clear indication in the code which PDEs have a split form and which don't.

**Comment by jbrillon** [comment]
I think that `PhysicsBase` can have a definition for the virtual function where there's an `std::abort` with a message; that way if someone tries calling it and hasn't implemented it, they'll receive the error message
