### ISSUE TITLE
Ensure time-accurate solver finishes at prescribed time

### ISSUE THREAD

**Issue by dougshidong** [dougshidong/PHiLiP#142]
See conversation:
https://github.com/dougshidong/PHiLiP/pull/138#discussion_r866264450

This is important to retain correct OOA.

**Comment by dougshidong** [comment]
@jbrillon @cpethrick @AlexanderCicchino , by now, this must be fixed for you guys to run your test cases right? Is it part of ODESolver?

**Comment by cpethrick** [comment]
I believe so. As of PR #215, we have the option of either reducing time step size to reach a specific end time, or taking time steps until the end time is reached/exceeded (which I use for OOA). @jbrillon can you confirm that there's no more work needed for this?

The fixes I'm aware of are done through flow solver. I don't currently use ODE solver to run cases, rather building my tests around flowsolver.

**Comment by jbrillon** [comment]
I believe we can close this issue, all of my runs end at the exact specified final time.
