### ISSUE TITLE
Move functionality of mesh adaptation to the flow solver.

### ISSUE THREAD

**Issue by PranshulThakur** [dougshidong/PHiLiP#159]
Currently, mesh adaptation is performed within ODESolverBase::steady_state(). To make the functions of ODESolver and MeshAdaptation separate, it would be better to move mesh adaptation to flow solver in future and call MeshAdaptation::adapt_mesh() after ODESolverBase::steady_state(). Some tests (such as the S-shock) do not use flow solver yet and these need to be modified to use the flow solver framework.

**Comment by jbrillon** [comment]
See comment in PR #155 : https://github.com/dougshidong/PHiLiP/pull/155#discussion_r913108351
