### ISSUE TITLE
Test 1D_BURGERS_ENERGY_CONSERVATION_RRK fails

### ISSUE THREAD

**Issue by cpethrick** [dougshidong/PHiLiP#165]
`1D_BURGERS_ENERGY_CONSERVATION_RRK`, introduced in PR #152, is currently failing due to the same periodic boundaries bug which is identified by issue #86. This bug is resolved by PR #111. Therefore, 1D_BURGERS_ENERGY_CONSERVATION_RRK is expected to pass without modification once PR #111 is merged.

**Comment by jbrillon** [comment]
Addressed by PR #111
