### ISSUE TITLE
TGV Tests failing on latest master

### ISSUE THREAD

**Issue by ssaishruthi98** [dougshidong/PHiLiP#247]
The TGV tests are failing on the latest master. 
![TGVTestsFailing](https://github.com/dougshidong/PHiLiP/assets/64045004/53be1c8e-f40f-4a97-84e0-3d7dc96bf633)

They fail with the following error
![TGVverboseoutput](https://github.com/dougshidong/PHiLiP/assets/64045004/01bf3267-24a7-4370-87bc-5ab8f64087e7)

**Comment by dougshidong** [comment]
Looking into it.
