### ISSUE TITLE
Abort if P>5 and using cPlus

### ISSUE THREAD

**Issue by jbrillon** [dougshidong/PHiLiP#252]
Add abort statement if using cPlus with P>5 since it is not defined.

**Comment by cpethrick** [comment]
I have a fix to this in PR #195. I have resumed work on that PR and hope to have it ready for review in the next week or so. 

Alternatively, I can move that fix into another PR if it's important to fix sooner.

Possibly related to this issue: the cPlus values are a function of the RK order. Currently, one set is just commented and must be uncommented if the user is changing the RK order. It's done this way as operators has no access to RK order or a parameters object. It wouldn't be too complex to fix, however we would need to change a lot of constructors.
