### ISSUE TITLE
MPI_2D_ADVECTION_EXPLICIT_PERIODIC_LONG passes no matter what

### ISSUE THREAD

**Issue by dougshidong** [dougshidong/PHiLiP#30]
MPI_2D_ADVECTION_EXPLICIT_PERIODIC_LONG will pass no matter what in Release mode since it return 0.

https://github.com/dougshidong/PHiLiP/blob/master/src/testing/advection_explicit_periodic.cpp#L103

Please fix such that the test fails for invalid answers. Since it is linear advection, the exact solution about time T is known. Convergence orders can/should be checked.

@abtin98

**Comment by jbrillon** [comment]
Addressed by PR #111
