### ISSUE TITLE
MPI_3D_EULER_SPLIT_TAYLOR_GREEN passes no matter what

### ISSUE THREAD

**Issue by dougshidong** [dougshidong/PHiLiP#32]
Return 0 no matter what.

https://github.com/dougshidong/PHiLiP/blob/efc614b48cfb4915c2dc7572de18a4179c4916eb/src/testing/euler_split_inviscid_taylor_green_vortex.cpp#L169

Should check that kinetic energy does not increase as done for the burgers_stability test

https://github.com/dougshidong/PHiLiP/blob/efc614b48cfb4915c2dc7572de18a4179c4916eb/src/testing/burgers_stability.cpp#L97-L101

@abtin98

**Comment by jbrillon** [comment]
Addressed by PR #111
