### ISSUE TITLE
Strong DG convergence orders

### ISSUE THREAD

**Issue by dougshidong** [dougshidong/PHiLiP#5]
Interpolating the flux using an order P polynomial results in a loss of order for even P. This happens for nonlinear problems, but not for linear advection.

No tests currently fail, but using an existing nonlinear problem (like 1D Burgers or Euler), and setting
`set use_weak_form = false`
will demonstrate the loss of convergence.

This can be resolved by interpolating (or maybe we should be projecting according to Jameson (2012) and Zwanenburg (2016) ) to a P+1 polynomial.

An earlier attempt has been made to project the flux to an order P polynomial (check branch `flux_projection`) and overintegrating this projection. No success with a P polynomial. 

Another possible source of error could be that the strong form is not adjoint consistent. Harriman et al. (2002) show that an adjoint inconsistent discretization results in a P convergence for even, and P+1 convergence for odd, just like we're witnessing.

**Comment by dougshidong** [comment]
Looks like you can possibly get away with projecting the flux to a polynomial of order P if you use GLL nodes for the solution points... We're still investigating.

**Comment by jbrillon** [comment]
Addressed by PR #111
