### ISSUE TITLE
Remove duplication of create_collection_tuple

### ISSUE THREAD

**Issue by dougshidong** [dougshidong/PHiLiP#65]
The lines of `OperatorBase::create_collection_tuple` have obviously been copied from DGBase. We should avoid copies and instead have a common function that both DGBase and OperatorBase calls.

https://github.com/dougshidong/PHiLiP/blob/9f4aa1fc9390836da4faf1fbf9ed76088192e537/src/operators/operators.cpp#L93-L202

**Comment by AlexanderCicchino** [comment]
Assign it to me
