### ISSUE TITLE
Use PhysicsBase's implementation of boundary_face_values in derived classes

### ISSUE THREAD

**Issue by dougshidong** [dougshidong/PHiLiP#72]
Right now, the when a manufactured solution boundary condition is imposed, the derived classes copied the function definition in the base class. Ideally, we want something like

```
DerivedClass::boundary_face_values() {
    if (manufactured_BC_id) {
        BaseClass::boundary_face_values()
    }
}
```

**Comment by jbrillon** [comment]
So that `boundary_face_values` is purely virtual in physics.cpp, will have to update the derived classes with `virtual` definition
